### ISSUE TITLE
Error when compiling github.com/tgulacsi/goracle/oracle

### ISSUE THREAD

**Issue by josesanchezr** [tgulacsi/goracle#27]
\# github.com/tgulacsi/goracle/oracle
../../../../github.com/tgulacsi/goracle/oracle/connection.go:23:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.

**Comment by josesanchezr** [comment]
Solved:
1. Go to $GOPATH/src/github.com/tgulacsi/goracle.
2. Run script "env" with: ./env

It should show something like:

cdir=/usr/include/oracle/12.1/client64 ldir=/usr/lib/oracle/12.1/client64/lib
export ORACLE_HOME=
export CGO_CFLAGS=-I/usr/include/oracle/12.1/client64
export CGO_LDFLAGS=-L/usr/lib/oracle/12.1/client64/lib

But shows nothing may be because you have set the environment variables: CGO_CFLAGS and CGO_LDFLAGS
3. Run: go get github.com/tgulacsi/goracle/godrv
4. Ready. With these steps, you should compile this library.

**Comment by tgulacsi** [comment]
Ok, I've tried to expand usage of . ./env.
