### ISSUE TITLE
Data race at /github.com/tgulacsi/goracle/oracle/cursor.go

### ISSUE THREAD

**Issue by vsdutka** [tgulacsi/goracle#28]
I have found Data Race at 

WARNING: DATA RACE
Write by goroutine 8:
  hash/fnv.(*sum64a).Reset()
     /src/hash/fnv/fnv.go:56 +0x3d
  github.com/tgulacsi/goracle/oracle.hashTag()
     src/github.com/tgulacsi/goracle/oracle/cursor.go:1913 +

**Comment by tgulacsi** [comment]
Yes, I was too smart reusing a global hasher. I'll fix it soon.

**Comment by tgulacsi** [comment]
It is fixed on the canonical repo, github.com/go-goracle/goracle, v1 branch.
